# Generated by Django 4.0.3 on 2022-03-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ime2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmodel',
            name='popis',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
